---
- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-grafana-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Create templates subdirectory
  file:
    state: directory
    path: "{{ tempdir }}/{{ item }}"
    mode: 0755
  changed_when: False
  with_items:
    - templates

- include_tasks: install_grafana.yaml
  when: openshift_grafana_state == 'present'

- include_tasks: uninstall_grafana.yaml
  when: openshift_grafana_state == 'absent'

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
