---
- name: Gather facts
  openshift_facts:
    role: common

- block:
    - name: Determine if excluder packages are installed
      rpm_q:
        name: "{{ openshift.common.service_type }}-excluder"
        state: present
      register: openshift_excluder_installed
      failed_when: false

    - name: unexclude the atomic package
      command: atomic-openshift-excluder unexclude
      when:
        - "{{ openshift_excluder_installed.installed_versions | default([]) | length > 0 }}"

    - name: Unexclude docker package
      command: atomic-openshift-docker-excluder unexclude
      when:
        - "{{ openshift_excluder_installed.installed_versions | default([]) | length > 0 }}"

  when: not openshift.common.is_atomic | bool
