---
- name: Create the demo project
  command: oc new-project demo

- name: Create MLB project
  shell: oc create -f https://raw.githubusercontent.com/gshipley/openshift3mlbparks/master/mlbparks-template-eap.json

- name: Create the new app
  shell: oc new-app --template="mlbparks-eap"

- name: Wait for MLB build to complete
  shell: oc get pod | grep -v deploy | awk '/mlbparks-1-build/{ print $3 }'
  register: build_output
  until: build_output.stdout | search("Completed")
  retries: 30
  delay: 30

- name: check the status of the page
  shell: "curl -sI http://mlbparks-demo.{{ wildcard_zone }} | grep HTTP"
  register: page_status
  until: page_status.stdout | search("HTTP/1.1 200 OK")
  retries: 30
  delay: 10

- name: Present URL
  debug:
      msg: "Application is located http://mlbparks-demo.{{ wildcard_zone }}"
