---
- name: Register host
  redhat_subscription:
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    state: present
    pool: "^{{ rhsm_pool }}"
  register: register_result
  when: ansible_distribution == "RedHat"
