---
- name: Register host
  redhat_subscription:
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    state: present
    pool: "^{{ rhsm_pool }}"
  when: ansible_os_family == "RedHat"
