---
- name: Gather facts
  openshift_facts:
    role: common

- name: Install the required rpms
  package: name={{ item }} state=latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - python-httplib2
  when: not openshift.common.is_atomic | bool
