- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      # Group systems
      - instance-groups
- hosts: cluster_hosts
  gather_facts: no
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - rhn-subscription
- hosts: cluster_hosts
  gather_facts: no
  become: yes
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - rhn-repos
      - prerequisites
- hosts: cluster_hosts
  gather_facts: no
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - docker-storage-setup
- include: openshift-setup.yaml
- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      - registry-volume
- hosts: primary_master
  gather_facts: yes
  become: yes
  vars_files:
      - vars/main.yaml
  roles:
      - openshift-router
      - openshift-registry
- hosts: masters
  gather_facts: no
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - openshift-default-selector
