# vim: set ft=ansible:
# Configure the instances
- include: ../../../openshift-ansible/playbooks/byo/openshift-cluster/config.yml
  vars_files:
    - ../../../../ose-on-aws/refarch-ansible/playbooks/vars/main.yaml
  vars:
    openshift_debug_level: "{{ debug_level }}"
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    openshift_node_kubelet_args:
      max-pods:
      - "100"
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    openshift_master_logging_public_url: "https://kibana.{{ osm_default_subdomain }}"
    openshift_master_metrics_public_url: "https://metrics.{{ osm_default_subdomain }}/hawkular/metrics"
    osm_cluster_network_cidr: 172.16.0.0/16
    osm_use_cockpit: false
    openshift_registry_selector: "role=infra"
    openshift_router_selector: "role=infra"
    openshift_master_cluster_method: native
    openshift_cloudprovider_kind: aws
