---
- name: Create the validation project
  command: oc new-project validate

- name: Create Hello world app
  shell: oc new-app --template cakephp-example

- name: Wait for build to complete
  shell: oc get pod | grep -v deploy | awk '/cakephp-example-1-build/{ print $3 }'
  register: build_output
  until: build_output.stdout | search("Completed")
  retries: 30
  delay: 15

- name: Wait for App to be running
  shell: oc get pod | grep -v deploy | grep -v build  | awk '/cakephp-example-1-*/{print $3}'
  register: deployer_output
  until: deployer_output.stdout | search("Running")
  retries: 30
  delay: 15

- name: Sleep to allow for route propegation
  pause:
     seconds: 10
- name: check the status of the page
  uri:
     url: "http://cakephp-example-validate.{{ wildcard_zone }}"
     status_code: 200
     method: GET

- name: Delete the Project
  command: oc delete project validate
