---
- name: block access to the GCE metadata server
  command: iptables --wait -4 --insert OUTPUT -d 169.254.169.254 -m comment --comment "Prevent all users from reaching GCE API server" -j REJECT --reject-with icmp-host-prohibited

- name: enable root user access to the GCE metadata server
  command: iptables --wait -4 --insert OUTPUT -d 169.254.169.254 -j ACCEPT -m comment --comment "Enable root user to reach GCE API server" -m owner --uid-owner 0

- name: enable udp access to the GCE DNS
  command: iptables --wait -4 --insert OUTPUT -p udp -d 169.254.169.254 -j ACCEPT --destination-port 53 -m comment --comment "Enable udp access to the GCE DNS"

- name: enable tcp access to the GCE DNS
  command: iptables --wait -4 --insert OUTPUT -p tcp -d 169.254.169.254 -j ACCEPT --destination-port 53 -m comment --comment "Enable tcp access to the GCE DNS"

- name: block containers from access to the GCE metadata server
  command: iptables --wait -4 --insert FORWARD -d 169.254.169.254 -m comment --comment "Prevent containers from reaching GCE API server" -j REJECT --reject-with icmp-host-prohibited
