---
- name: Add gluster instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
  with_items: "{{ groups['tag_StorageType_crs'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}-{{ gluster_stack }}"
