---
- name: Get facts of production VMs
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{ item.value.guestname }}"
  register: actual_production_hosts
  with_dict: "{{ production_hosts }}"
  until:  actual_production_hosts.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Update production VMs inventory to assign hostname
  add_host: hostname={{item.ansible_facts.hw_name}} ansible_ssh_host="{{item.item.value.guestname}}.{{public_hosted_zone}}" groups="production_group, {{ item.item.value.tag }}"
  with_items: "{{ actual_production_hosts.results }}"
  ignore_errors: yes
