---
- name: ensure the cloudprovider folder exists
  file:
    name: "{{ openshift.common.config_base }}cloudprovider"
    state: directory
    recurse: yes

- name: configure gce cloud config options
  ini_file:
    dest: "{{ openshift.common.config_base }}cloudprovider/gce.conf"
    section: global
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    create: yes
  with_items:
    - { key: 'project-id', value: '{{ gcloud_project }}' }
    - { key: 'network-name', value: '{{ prefix }}-network' }
    - { key: 'node-tags', value: '{{ prefix }}' }
    - { key: 'node-instance-prefix', value: '{{ prefix }}-' }
    - { key: 'multizone', value: 'false' }
