---
- name: ensure the /etc/origin/cloudprovider folder exists
  file:
    name: "{{ openshift.common.config_base }}cloudprovider"
    state: directory
    recurse: yes

- name: configure gce cloud config options
  ini_file:
    dest: /etc/origin/cloudprovider/gce.conf
    section: global
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    create: yes
  with_items:
    - { key: 'project-id', value: '{{ gce_project_id }}' }
    - { key: 'network-name', value: '{{ gce_network_name }}' }
    - { key: 'node-tags', value: 'ocp' }
    - { key: 'node-instance-prefix', value: 'ocp-' }
    - { key: 'multizone', value: 'false' }
