---
- name: ensure the /etc/orgin folder exists
  file: name=/etc/origin state=directory

- name: configure gce cloud config options
  ini_file: dest=/etc/origin/gce.ini section=global option={{ item.key }} value={{ item.value }} state=present
  with_items:
    - { key: 'project-id', value: '{{ gce_project_id }}' }
    - { key: 'network-name', value: '{{ gce_network_name }}' }
    - { key: 'node-tags', value: 'ocp' }
    - { key: 'node-instance-prefix', value: 'ocp-' }
    - { key: 'multizone', value: 'false' }
