---
- name: Add DNS entry to Route53
  route53:
     command: create
     zone: "{{ public_hosted_zone }}"
     record: "bastion.{{ public_hosted_zone }}"
     type: A
     ttl: 7200
     value: "{{ eip.public_ip }}"
     overwrite: yes
