---
- name: create core infrastructure
  hosts: localhost
  roles:
  - ssl-certificate
  - role: deployment-create
    deployment_name: core
  post_tasks:
  - name: wait for instance groups to be ready
    include_role:
      name: wait-for-instance-group
    with_items:
    - '{{ prefix }}-master'
    - '{{ prefix }}-node'
    - '{{ prefix }}-infra-node'
    loop_control:
      loop_var: instance_group
  - name: refresh gce inventory
    command: '{{ inventory_dir }}/gce/hosts/gce.py --refresh-cache'
    changed_when: false
  - meta: refresh_inventory

- name: continue with the core infrastructure deployment, after the instances are created
  hosts: localhost
  roles:
  - dns-records
  - ssh-proxy

# Ansible bug keeps this from working through the bastion host
# https://github.com/ansible/ansible/issues/23774
#- hosts: all
#  tasks:
#  - name: wait for instances to become available
#    wait_for_connection:
#      timeout: 900
- name: wait for instances to become available for ssh
  hosts: 'tag_{{ prefix }}-bastion:tag_{{ prefix }}'
  tasks:
  - name: ping hosts
    action: ping
    register: ping_result
    until: ping_result.ping == 'pong'
    retries: 50
    delay: 3
    changed_when: false
    ignore_errors: true
