---
- name: create temp instance for gold image creation
  hosts: localhost
  roles:
  - role: deployment-create
    deployment_name: tmp-instance
  post_tasks:
  - name: refresh gce inventory
    command: '{{ inventory_dir }}/gce/hosts/gce.py --refresh-cache'
    changed_when: false
  - meta: refresh_inventory
  - name: wait for the temp instance to come up
    wait_for:
      host: '{{ ocp_tmp_instance }}'
      port: 22
      state: started

- name: modify temp instance
  hosts: '{{ ocp_tmp_instance }}'
  vars_files:
  - ../../ansible-main-config.yaml
  roles:
  - gold-image-instance

- name: create gold image from temp instance disk
  hosts: localhost
  roles:
  - role: deployment-delete
    deployment_name: tmp-instance
  - gold-image
