---
- name: configure ansible connection to the gcp
  hosts: localhost
  vars_files:
  - ../../ansible-main-config.yaml
  roles:
  - ansible-gcp
  - dns-zone
  - rhel-image
  - gcp-ssh-key
  - { role: deployment-manager, deployment_name: '{{ network_deployment }}' }
