---
- name: disable unneeded repos
  command: subscription-manager repos --disable='*'
  when: register_result | changed and ansible_distribution == "RedHat"

- name: ensure proper repos are assigned
  command: subscription-manager repos --enable={{ item }}
  with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.3-rpms
  when: ansible_distribution == "RedHat"

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: ansible_distribution != "RedHat"


- name: Import EPEL GPG key.
  rpm_key:
    key: "http://mirror.sfo12.us.leaseweb.net/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when: ansible_distribution != "RedHat"
