---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - gluster-instance-groups

- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - rhsm-subscription
  - gluster-rhsm-repos
  - gluster-crs-prerequisites
  - gluster-ports
