---
- name: Running the scaleup playbook
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - name: Include variables
    include_vars: vars/aws_openshift.yaml

  - include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml
