---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - cfn-outputs
  - instance-groups

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - host-up

- include: ../../../playbooks/prerequisite.yaml

- include: ../../../playbooks/unexclude-atomic-docker.yaml

- include: openshift-setup.yaml

- include: ../../../playbooks/exclude-atomic-docker.yaml
