- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  pre_tasks:
      - name: set fact
        set_fact:
           openshift_master_cluster_public_hostname: "{{ openshift_master_cluster_public_hostname }}"
      - name: set fact
        set_fact:
           openshift_master_cluster_hostname: "{{ openshift_master_cluster_hostname }}"
  roles:
      # Group systems
      - instance-groups

<<<<<<< HEAD
- include: ../../../playbooks/validation.yaml
=======
- include: ../../../playbooks/post-install-check.yaml
>>>>>>> a30e0f47c3b256ee8a0072c96d23a32617078e53
