- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  pre_tasks:
      - name: set fact
        set_fact:
           openshift_master_cluster_public_hostname: "openshift-master.{{ public_hosted_zone }}"
      - name: set fact
        set_fact:
           openshift_master_cluster_hostname: "internal-openshift-master.{{ public_hosted_zone }}"
  roles:
      # Group systems
      - instance-groups

- include: ../../common/validation.yaml
