---
- name: Identify mixed instack/external DNS servers cases
  block:
    - set_fact:
        pub_instack: False
        priv_instack: False
        priv_pub_access: False

    - set_fact:
        pub_instack: "{{ external_nsupdate_keys[public].instack|default(False)|bool }}"
      when: external_nsupdate_keys[public] is defined

    - set_fact:
        priv_instack: "{{ external_nsupdate_keys[private].instack|default(False)|bool }}"
        priv_pub_access: "{{ external_nsupdate_keys[private].public_access|default(False)|bool }}"
      when: external_nsupdate_keys[private] is defined

- fail:
    msg: 'Missing required private DNS server(s)'
  when:
    - external_nsupdate_keys[private] is undefined
    - hostvars[groups['dns'][0]] is undefined

- fail:
    msg: 'Missing required public DNS server(s)'
  when:
    - external_nsupdate_keys[public] is undefined
    - hostvars[groups['dns'][0]] is undefined

- include: autoeval_nsupdate_facts.yml
