---
- name: Update configured DNS nsupdate keys for mixed instack cases
  block:
    - when:
      - external_nsupdate_keys[public] is defined
      - pub_instack
      set_fact:
        external_nsupdate_keys:
          public: >-
            {%- if hostvars[groups['dns'][0]].nsupdate_keys is defined -%}
            {{ external_nsupdate_keys[public] | combine({
            'server' : public_dns_server,
            'key_algorithm' : public_key_algorithm,
            'key_secret' : public_key_secret }) }}
            {%- else -%}
            {{ external_nsupdate_keys[public] | combine({
            'server' : public_dns_server }) }}
            {%- endif -%}
          private: "{{ external_nsupdate_keys[private] }}"

    - when:
      - external_nsupdate_keys[private] is defined
      - priv_instack
      set_fact:
        external_nsupdate_keys:
          public: "{{ external_nsupdate_keys[public] }}"
          private: >-
            {%- if hostvars[groups['dns'][0]].nsupdate_keys is defined -%}
            {{ external_nsupdate_keys[private] | combine({
            'server' : private_dns_server,
            'key_algorithm' : private_key_algorithm,
            'key_secret' : private_key_secret }) }}
            {%- else -%}
            {{ external_nsupdate_keys[private] | combine({
            'server' : private_dns_server }) }}
            {%- endif -%}

- debug:
    var: external_nsupdate_keys
  when: priv_instack or pub_instack
