---
stack_name: "{{ env_id }}.{{ public_dns_domain }}"
dns_domain: "{{ public_dns_domain }}"
dns_nameservers: "{{ public_dns_nameservers }}"
subnet_prefix: "{{ openstack_subnet_prefix }}"
ssh_public_key: "{{ openstack_ssh_public_key }}"
openstack_image: "{{ openstack_default_image_name }}"
lb_flavor: "{{ openstack_lb_flavor | default(openstack_default_flavor) }}"
etcd_flavor: "{{ openstack_etcd_flavor | default(openstack_default_flavor) }}"
master_flavor: "{{ openstack_master_flavor | default(openstack_default_flavor) }}"
node_flavor: "{{ openstack_node_flavor | default(openstack_default_flavor) }}"
infra_flavor: "{{ openstack_infra_flavor | default(openstack_default_flavor) }}"
dns_flavor: "{{ openstack_dns_flavor | default(openstack_default_flavor) }}"
openstack_master_image: "{{ openstack_master_image_name | default(openstack_default_image_name) }}"
openstack_infra_image: "{{ openstack_infra_image_name | default(openstack_default_image_name) }}"
openstack_node_image: "{{ openstack_node_image_name | default(openstack_default_image_name) }}"
openstack_lb_image: "{{ openstack_lb_image_name | default(openstack_default_image_name) }}"
openstack_etcd_image: "{{ openstack_etcd_image_name | default(openstack_default_image_name) }}"
openstack_dns_image: "{{ openstack_dns_image_name | default(openstack_default_image_name) }}"
openstack_private_network: "{{ openstack_private_network_name | default ('openshift-ansible-' + stack_name + '-net') }}"
external_network: "{{ openstack_external_network_name }}"
num_etcd: "{{ openstack_num_etcd | default(0) }}"
num_masters: "{{ openstack_num_masters }}"
num_nodes: "{{ openstack_num_nodes }}"
num_infra: "{{ openstack_num_infra }}"
num_dns: "{{ openstack_num_dns | default(1) }}"
master_volume_size: "{{ docker_volume_size }}"
app_volume_size: "{{ docker_volume_size }}"
infra_volume_size: "{{ docker_volume_size }}"
nodes_to_remove: "{{ openstack_nodes_to_remove | default([]) |  to_yaml }}"
use_bastion: "{{ openstack_use_bastion|default(False) }}"
ui_ssh_tunnel: "{{ openshift_ui_ssh_tunnel|default(False) }}"
