---
- name: Network Restart to activate new interface
  service: name=network state=restarted
  ignore_errors: true

- name: Clear yum cache
  command: "yum clean all"
  ignore_errors: true

- name: Install the required rpms
  package: name="{{ item }}" state=latest
  with_items:
  - NetworkManager
  - iptables-services


- name: Start NetworkManager
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - NetworkManager
  - iptables
