---
- name: Network Restart to activate new interface
  service: name=network state=restarted
  ignore_errors: true

- name: Clear yum cache
  command: "yum clean all"
  ignore_errors: true 

- name: Install the required rpms
  yum: name={{ item }} state=latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - python-httplib2
      - atomic-openshift-utils
