---
# OpenShift variables
openshift_master_cluster_hostname: "{{ lb_host }}"
openshift_master_cluster_public_hostname: "{{ lb_host }}"
console_port: 8443
master_tag: master
infra_tag: infra
app_tag: app
master_group_tag: "tag_openshift-role_{{ master_tag }}"
app_group_tag: "tag_openshift-role_{{ app_tag }}"
infra_group_tag: "tag_openshift-role_{{ infra_tag }}"
