---
debug_level: 2
console_port: 8443
openshift_debug_level: "{{ debug_level }}"
openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
osm_controller_args:
osm_api_server_args:
openshift_node_kubelet_args:
  node-labels:
  - "role={{ openshift_node_labels.role }}"
openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
openshift_master_access_token_max_seconds: 2419200
openshift_master_api_port: "{{ console_port }}"
openshift_master_console_port: "{{ console_port }}"
osm_cluster_network_cidr: 172.16.0.0/16
openshift_registry_selector: "role=infra"
openshift_router_selector: "role=infra"
openshift_node_local_quota_per_fsgroup: 512Mi
openshift_master_cluster_method: native
openshift_cloudprovider_kind: vsphere
deployment_type:
load_balancer_hostname:
openshift_master_cluster_hostname: "{{ load_balancer_hostname }}"
openshift_master_cluster_public_hostname: "{{ load_balancer_hostname }}"
osm_default_node_selector: "role=app"
openshift_hosted_router_replicas: 2
openshift_hosted_registry_replicas: 1
openshift_master_logging_public_url: "https://kibana.{{ osm_default_subdomain }}"
openshift_master_metrics_public_url: "https://metrics.{{ osm_default_subdomain }}/hawkular/metrics"
osm_use_cockpit: false
openshift_override_hostname_check: true
wildcard_zone:
osm_default_subdomain: "{{ wildcard_zone }}"
openshift_master_default_subdomain: "{{ osm_default_subdomain }}"
os_sdn_network_plugin_name: "redhat/{{ openshift_sdn }}"
openshift_master_identity_providers:
- name: Active_Directory
  challenge: true
  login: true
  kind: LDAPPasswordIdentityProvider
  attributes:
    id:
    - dn
    email:
    - mail
    name:
    - cn
    preferredUsername:
    - uid
  insecure: true
  url:
  bindDN:
  bindPassword:
openshift_hosted_registry_storage_kind: nfs
openshift_hosted_registry_storage_access_modes: ['ReadWriteMany']
openshift_hosted_registry_storage_host:
openshift_hosted_registry_storage_nfs_directory:
openshift_hosted_registry_storage_volume_name: registry
openshift_hosted_registry_storage_volume_size: 30Gi
