---
- name: open gluster ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 24007/tcp
    - 8080/tcp
    - 24008/tcp
    - 2222/tcp
    - 49152-49664/tcp
- name: force a reload of firewalld
  command: /bin/firewall-cmd --reload
