---
- name: open gluster ports
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: tcp
    match: tcp
  with_items:
    - 24007
    - 8080
    - 24008
    - 2222
    - 49152:49664
