---
- hosts: bastion
  roles:
    - e2e_vcenter_host
    - bastion
  tags: ["bastion", "infrastructure"]

  tasks:
  - name: Copy PersistentVolume json files to bastion host
    copy: src=persistent-volume.{{ item }}.json dest=/root/
    with_sequence: start={{osnl_volume_num_start}} count={{osnl_number_of_volumes}} format=pv{{osnl_volume_size}}g%04d
    ignore_errors: true
    when: inventory_hostname == 'bastion'
    tags: ['testing', 'production', 'bastion', 'infrastructure']

  - name: clone openshift-ansible from github.com
    command: git clone https://github.com/openshift/openshift-ansible
    ignore_errors: true
    when: inventory_hostname == 'bastion'
    tags: ['testing', 'production', 'bastion', 'infrastructure']

  - name: clone ose-on-vmware from https://gitlab.cee.redhat.com/e2e/ose-on-vmware
    command: env GIT_SSL_NO_VERIFY=true git clone https://gitlab.cee.redhat.com/e2e/ose-on-vmware.git
    ignore_errors: true
    when: inventory_hostname == 'bastion'
    tags: ['testing', 'production', 'bastion', 'infrastructure']

  - name: Install OpenShift Enterprise clients
    action: "{{ ansible_pkg_mgr }} name=atomic-openshift-clients state=present"
    when: inventory_hostname == 'bastion'
    tags: ['testing', 'production', 'bastion', 'infrastructure']
