---
- name: Create VM to be used as a template on vCenter
  hosts: localhost
  user: root
  become: false
  vars_files:
    - vars/main.yaml

  tags: ['template', 'infrastructure']

  tasks:
  - name: create VM on vCenter
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster: "{{ cluster}}"
      guest: "ose3-server-template-2.0.2"
      esxi:
        datacenter: "{{datacenter}}"
        hostname: "10.19.114.222"
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: "Create by Ansible to be used as a template"
      vm_disk:
        disk1:
          size_gb: 32
          type: "thin"
          datastore: "ose3-vmware"
      vm_nic:
        nic1:
          type: vmxnet3
          network: "VM Network"
          network_type: standard
      vm_hardware:
        memory_mb: 4096
        num_cpus: 2
        osid: rhel64Guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "ose3-vmware/ISOs/rhel-server-7.2-x86_64-dvd.iso"

    tags: ['template', 'infrastructure', 'vm_creation']

  - name: get facts of VM
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      vmware_guest_facts: yes
      guest: "ose3-server-template-2.0.0"
    register: actual_template_guest
    until: actual_template_guest.ansible_facts.hw_eth0.ipaddresses[0] is defined
    retries: 10
    delay: 10
    tags: ['template', 'infrastructure']

  - name: add template VM to inventory
    add_host: hostname="ose3-server-template-2.0.0" ansible_ssh_host="{{actual_template_guest.ansible_facts.hw_eth0.ipaddresses[0]}}" groups="template"
    tags: ['tempalte', 'infrastructure']
