---
- name: Deploy NFS server
  hosts: nfs_group
  user: root
  become: false
  vars_files:
    - ../vars/main.yaml
    - ../vars/infrastructure.yaml
  tags: ['nfs', 'infrastructure']

- name: Provision NFS server
  hosts: nfs_group
  user: root
  become: false
  vars_files:
    - ../vars/main.yaml
    - ../vars/infrastructure.yaml

  roles:
    - static_ipaddress
    - e2e_vcenter_host
    - nfs_server

  tags: ['nfs', 'infrastructure']
