---
- name: Creating AWS Keypair
  ec2_key:
    key_material: "{{ lookup('file', '~/.ssh/' + clusterid + '.' + dns_domain + '.pub') | expanduser }}"
    name: "{{ clusterid }}.{{ dns_domain }}"
    region: "{{ aws_region }}"
    state: present
  with_file: "~/.ssh/{{ clusterid }}.{{ dns_domain }}.pub"
