---
- name: "Create VPC DHCP Options"
  ec2_vpc_dhcp_options:
    domain_name: "ec2.internal"
    region: "{{ aws_region }}"
    dns_servers:
      - AmazonProvidedDNS
    inherit_existing: False
  retries: 3
  delay: 3
  register: vpcdhcpopts

- include_tasks: tag.yaml
  vars:
    - resource: "{{ vpcdhcpopts.dhcp_options_id }}"
    - tagss: { 'Name': "{{ clusterid }}", 'Clusterid': "{{ clusterid }}" }
  when: vpcdhcpopts.changed
