---
- name: Create VM on vCenter
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster: "{{ vcenter_cluster}}"
    resource_pool: "{{ vcenter_resource_pool }}"
    guest: "{{ item.value.guestname }}"
    from_template: yes
    template_src: "{{ vcenter_template_name }}"
    power_on_after_clone: true
    vm_extra_config:
      folder: "{{ vcenter_folder }}"
      notes: "infrastructure-auth"
    esxi:
      datacenter: "{{ vcenter_datacenter }}"
      hostname: "10.19.114.222"
  with_dict: "{{infrastructure_hosts}}"
  when: item.value.guestname == 'auth-proxy-0'

- name: Get facts of auth proxy VM
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{infrastructure_hosts.auth_proxy_0.guestname}}"
  register: actual_auth_proxy_host
  until: actual_auth_proxy_host.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Add auth proxy to inventory
  add_host: hostname="{{infrastructure_hosts.auth_proxy_0.guestname}}" ansible_ssh_host="{{actual_auth_proxy_host.ansible_facts.hw_eth0.ipaddresses[0]}}" groups="auth_proxy"
