---
- name: Create router ELB
  ec2_elb_lb:
     name: "ose-router-elb"
     state: present
     subnets:
         - "{{ subnet1 }}"
         - "{{ subnet2 }}"
         - "{{ subnet3 }}"
     security_group_ids: "{{ router_elb_sg.group_id }}"
     region: "{{ region }}"
     listeners:
       - protocol: tcp
         load_balancer_port: 80
         instance_protocol: tcp
         instance_port: 80
       - protocol: tcp
         load_balancer_port: 443
         instance_protocol: tcp
         instance_port: 443
     health_check:
         ping_protocol: tcp
         ping_port: 443
         response_timeout: 2
         interval: 5 # seconds
         unhealthy_threshold: 2
         healthy_threshold: 2
  register: router_elb
- name: Add instances to Router ELB
  ec2_elb:
     instance_id: "{{ item }}"
     ec2_elbs: ose-router-elb
     state: present
     region: "{{ region }}"
     wait: no
  with_items:
      - "{{ infra0.instance_ids }}"
      - "{{ infra1.instance_ids }}"
  ignore_errors: yes
