---
- name: Copying over your ssh public key VM
  authorized_key: user=root key= "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  ignore_errors: yes

- name: Setting hostname of VM
  hostname: name="{{host_inventory[inventory_hostname].guestname}}.{{public_hosted_zone}}"
  ignore_errors: yes

- name: Adding subinterface on network connection to use static addresses
  template: src=ifcfg-public.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ vm_interface_name }}:1" owner=root group=root mode=0644
  with_items:
    - ip4: "{{host_inventory[inventory_hostname].ip4addr}}"
      gw4: "{{ vm_gw }}"
      dns: "{{ vm_dns }}"
      device: "{{ vm_interface_name }}"
  when: hostvars[inventory_hostname].ansible_ssh_host != "{{host_inventory[inventory_hostname].ip4addr}}"

- name: Network Restart to activate new interface
  service: name=network state=restarted
  ignore_errors: true
  when: hostvars[inventory_hostname].ansible_ssh_host != "{{host_inventory[inventory_hostname].ip4addr}}"

- name: Reconfiguring public network interface to use static address with new file
  template: src=ifcfg-public.j3 dest=/etc/sysconfig/network-scripts/ifcfg-public owner=root group=root mode=0644
  with_items:
    - ip4: "{{host_inventory[inventory_hostname].ip4addr}}"
      gw4: "{{ vm_gw }}"
      dns: "{{ vm_dns }}"
  when: hostvars[inventory_hostname].ansible_ssh_host != "{{host_inventory[inventory_hostname].ip4addr}}"

- name: Ensure that the old ifcfgs are removed
  file: path=/etc/sysconfig/network-scripts/{{ item }} state=absent
  with_items:
    - "ifcfg-{{ vm_interface_name }}"
    - "ifcfg-{{ vm_interface_name }}:1"
  when: hostvars[inventory_hostname].ansible_ssh_host != "{{host_inventory[inventory_hostname].ip4addr}}"
