---
- name: Create NFS VM on vCenter
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ item.value.guestname }}"
    cluster: "{{ vcenter_cluster}}"
    resource_pool: "{{ vcenter_resource_pool }}"
    validate_certs: False
    from_template: yes
    template_src: "{{vcenter_template_name}}"
    vm_extra_config:
      notes: "{{ item.value.tag }}"
      folder: "{{ vcenter_folder }}"
  with_dict: "{{infrastructure_hosts}}"
  when: item.value == 'nfs_server'

- name: Get facts of NFS VM
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{ infrastructure_hosts.nfs_server.guestname }}"
  register: actual_nfs_host
  until: actual_nfs_host.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Add NFS server to inventory
  add_host: hostname={{actual_nfs_host.ansible_facts.hw_name}} ansible_ssh_host={{actual_nfs_host.ansible_facts.hw_eth0.ipaddresses[0]}} groups="nfs_group"
