---
- name: Create testing VMs on vCenter
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ item.value.guestname }}"
    cluster: "{{ vcenter_cluster}}"
    resource_pool: "{{ vcenter_resource_pool }}"
    from_template: yes
    template_src: "{{template_name}}"
    power_on_after_clone: true
    vm_extra_config:
      folder: "{{ folder }}"
      notes: "{{ item.value.tag }}"
    esxi:
      datacenter: "{{datacenter}}"
      hostname: "10.19.114.222"
  with_dict: "{{ testing_hosts }}"

- name: Get facts of testing VMs
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{ item.value.guestname }}"
  register: actual_testing_hosts
  with_dict: "{{ testing_hosts }}"
  until:  actual_testing_hosts.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Add testing VMs to inventory
  add_host: hostname={{item.ansible_facts.hw_name}} ansible_ssh_host={{item.ansible_facts.hw_eth0.ipaddresses[0]}} groups="testing_group, {{ item.item.value.tag }}"
  with_items: "{{ actual_testing_hosts.results }}"
  ignore_errors: yes

- name: Add testing VMs to inventory
  add_host: hostname={{item.ansible_facts.hw_name}} ansible_ssh_host={{item.ansible_facts.hw_eth0.ipaddresses[1]}} groups="testing_group, {{ item.item.value.tag }}"
  with_items: "{{ actual_testing_hosts.results }}"
  when: actual_testing_hosts.ansible_facts.hw_eth0.ipaddresses[1] is defined
  ignore_errors: yes
