---
- name: set ssh proxy command prefix for accessing nodes via bastion
  set_fact:
    ssh_proxy_command: >-
      ssh {{ ssh_options }}
      -i {{ private_ssh_key }}
      {{ ssh_user }}@{{ hostvars[groups.bastions[0]].public_v4 }}

- name: regenerate ssh config
  template:
    src: openstack_ssh_config.j2
    dest: "{{ ssh_config_path }}"
    mode: 0644
