---
- name: Add bastion to group
  add_host:
    name: "bastion.{{ public_hosted_zone }}"
    groups: bastion
  when:
    - byo_bastion == "no"

- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: masters, etcd, nodes, cluster_hosts
  with_items: "{{ groups['tag_openshift_role_master'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}"

- name: Add a master to the single master group
  add_host:
    name: "{{ item }}"
    groups: single_master
  with_items: "{{ groups['masters'].0 }}"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
  with_items: "{{ groups['tag_openshift_role_infra'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
  with_items: "{{ groups['tag_openshift_role_app'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == "{{ stack_name }}"
