---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - create-vm-add-prod-ose 
  - instance-groups

- hosts: new_nodes
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - rhsm-subscription
  - rhsm-repos
  - vmware-guest-setup
- include: ../../../playbooks/openshift-storage.yaml
- include: ../../../playbooks/add-node-prerequisite.yaml

- include: node-setup.yaml

- hosts: loadbalancer, master, infra
  gather_facts: yes 
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - haproxy-server-config
 
