---
- hosts: localhost
  gather_facts: yes
  vars_files:
      - ../vars/main.yaml
  roles:
      # Group systems
      - instance-groups

- hosts: schedulable_nodes
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yaml
  roles:
      - openshift-emptydir-quota

- hosts: primary_master
  gather_facts: yes
  become: yes
  vars_files:
      - ../vars/main.yaml

  roles:
      - openshift-registry
