---
- hosts: localhost
  gather_facts: yes
  vars_files:
  - ../vars/main.yaml
  roles:
  # Group systems
  - instance-groups

- name: call openshift includes for installer
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/adhoc/uninstall.yml
  vars_files:
  - vars/vmware_openshift.yaml
