---
- hosts: localhost
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - instance-groups

- include: ../../../playbooks/prerequisite.yaml

- include: ../../../playbooks/openshift-storage.yaml

- name: Running the OCP installation playbook
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
  -  vars/aws_openshift.yaml
  tasks:
  - include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
