---
- hosts: localhost
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - instance-groups

- include: ../../../playbooks/prerequisite.yaml

- include: ../../../playbooks/openshift-storage.yaml

- name: call openshift includes for installer
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
  vars_files:
  - vars/vmware_openshift.yaml
