---
- hosts: localhost
  vars_files:
    - ../vars/main.yaml
  roles:
    - create-vm-nfs

- name: Deploy NFS server
  hosts: nfs_group
  vars_files:
    - ../vars/main.yaml

  roles:
    - static-ipaddress
    - rhsm-subscription
    - rhsm-repos
    - vmware-guest-setup
    - nfs-server
