---
- name: "Generate list of private A records"
  set_fact:
    private_records: "{{ private_records | default([]) + [ { 'type': 'A', 'hostname': hostvars[item]['ansible_hostname'], 'ip': hostvars[item]['private_v4'] } ] }}"
  with_items: "{{ groups['cluster_hosts'] }}"

- name: "Add wildcard records to the private A records for infrahosts"
  set_fact:
    private_records: "{{ private_records | default([]) + [ { 'type': 'A', 'hostname': '*.' + openshift_app_domain, 'ip': hostvars[item]['private_v4'] } ] }}"
  with_items: "{{ groups['infra_hosts'] }}"

- name: "Generate the private Add section for DNS"
  set_fact:
    private_named_records:
      - view: "private"
        zone: "{{ full_dns_domain }}"
        server: "{{ private_dns_server }}"
        key_name: "{{ private }}"
        key_secret: "{{ private_key_secret }}"
        key_algorithm: "{{ private_key_algorithm | lower }}"
        entries: "{{ private_records }}"

- name: "Generate list of public A records"
  set_fact:
    public_records: "{{ public_records | default([]) + [ { 'type': 'A', 'hostname': hostvars[item]['ansible_hostname'], 'ip': hostvars[item]['public_v4'] } ] }}"
  with_items: "{{ groups['cluster_hosts'] }}"
  when: hostvars[item]['public_v4'] is defined

- name: "Add wildcard records to the public A records"
  set_fact:
    public_records: "{{ public_records | default([]) + [ { 'type': 'A', 'hostname': '*.' + openshift_app_domain, 'ip': hostvars[item]['public_v4'] } ] }}"
  with_items: "{{ groups['infra_hosts'] }}"
  when: hostvars[item]['public_v4'] is defined

- name: "Generate the public Add section for DNS"
  set_fact:
    public_named_records:
      - view: "public"
        zone: "{{ full_dns_domain }}"
        server: "{{ public_dns_server }}"
        key_name: "{{ ( 'public-' + full_dns_domain ) }}"
        key_secret: "{{ public_key_secret }}"
        key_algorithm: "{{ public_key_algorithm | lower }}"
        entries: "{{ public_records }}"

- name: "Generate the final dns_records_add"
  set_fact:
    dns_records_add: "{{ private_named_records + public_named_records }}"
