---
- name: create the docker-storage-setup config file
  template:
    src: "{{ role_path }}/templates/docker-storage-setup.j2"
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
