---
- name: Ensure openshift-ansible installer package deps are installed
  package:
    name: "{{ 'python-ipaddress' if ansible_distribution != 'Fedora' else '' }}"
    state: present

- name: Gather facts
  openshift_facts:
    role: common

- name: create the docker-storage-setup config file
  template:
    src: "{{ role_path }}/templates/docker-storage-setup.j2"
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
  when: not openshift.common.is_atomic | bool and ansible_distribution != 'CentOS'

- name: create the docker-storage-setup config file
  template:
    src: "{{ role_path }}/templates/docker-storage-setup-dm.j2"
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'CentOS' and not openshift.common.is_atomic | bool
