---
- name: create additional disks
  include_role:
    name: deployment-create
  vars:
    deployment_name: add-disks
    instances: '{{ (groups["tag_ocp-infra-node"] + groups["tag_ocp-node"]) | map("extract", hostvars) | list | json_query("[].{name: gce_name, zone: gce_zone}") }}'

- name: attach additional docker disk to the instances
  gce_pd:
    name: '{{ prefix }}-pd-docker-{{ item }}'
    instance_name: '{{ item }}'
    zone: '{{ hostvars[item].gce_zone }}'
    mode: READ_WRITE
    state: active
  with_items: '{{ groups["tag_ocp-infra-node"] + groups["tag_ocp-node"] }}'

- name: attach additional openshift disk to the instances
  gce_pd:
    name: '{{ prefix }}-pd-openshift-{{ item }}'
    instance_name: '{{ item }}'
    zone: '{{ hostvars[item].gce_zone }}'
    mode: READ_WRITE
    state: active
  with_items: '{{ groups["tag_ocp-infra-node"] + groups["tag_ocp-node"] }}'
