---
- hosts: localhost
  gather_facts: yes
  roles:
    - instance-groups

- hosts: localhost
  gather_facts: no
  roles:
    - validate-public

- hosts: masters
  gather_facts: no
  roles:
    - validate-masters

- hosts: masters
  gather_facts: yes
  roles:
    - validate-etcd

- hosts: single_master
  gather_facts: no
  roles:
    - validate-app
