---
- hosts: localhost
  gather_facts: yes
  become: no
  pre_tasks:
  - name: set fact
    set_fact:
      openshift_master_cluster_public_hostname: "{{ openshift_master_cluster_public_hostname }}"
  - name: set fact
    set_fact:
      openshift_master_cluster_hostname: "{{ openshift_master_cluster_hostname }}"
  roles:
  # Group systems
  - instance-groups

- include: ../../../playbooks/post-validation.yaml
  vars:
    validate_etcd_short_hostname: true
