---
- name: create the docker-storage-setup config file
  copy: src=docker-storage-setup dest=/etc/sysconfig/docker-storage-setup owner=root group=root mode=0644
- name: start docker
  service: name=docker state=started
