---
- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: masters, etcd, nodes, cluster_hosts
    openshift_node_labels:
      role: master
  with_items: "{{ groups['master'] }}"

- name: Add a master to the primary masters group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: primary_master
    openshift_node_labels:
      role: master
  with_items:
    - master-0
  #"{{ groups['master'] }}"
  #when: 0 in "{{ hostvars[item].inventory_hostname }}"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: infra
  with_items: "{{ groups['infra'] }}"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].inventory_hostname }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: app
  with_items: "{{ groups['app'] }}"
